gerarErro2(100)
    .then(console.log)
    .catch(console.log) //Sem execeção